/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "CustomLookAndFeel.h"


//==============================================================================
/**
*/
class Fl2flangerAudioProcessorEditor  : public AudioProcessorEditor,
                                        public ChangeListener,
                                        public SliderListener
{
public:
    Fl2flangerAudioProcessorEditor (Fl2flangerAudioProcessor* ownerFilter);
    ~Fl2flangerAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
    void changeListenerCallback(ChangeBroadcaster* source);
    void sliderValueChanged(Slider* slider);
    void mouseDown (const MouseEvent &event) override;
    void mouseUp (const MouseEvent &event) override;
    
    Slider delaySlider, depthSlider, rateSlider, regenSlider, mixSlider;
    CustomLookAndFeel customLookAndFeel;
    
    Fl2flangerAudioProcessor* GetProcessor() const
    {
        return static_cast <Fl2flangerAudioProcessor*> (getAudioProcessor());
    }
    
};


#endif  // PLUGINEDITOR_H_INCLUDED
